name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/demo:latest
      - run: docker tag ${{ secrets.DOCKER_HUB_USERNAME }}/demo:latest ${{ secrets.DOCKER_HUB_USERNAME }}/demo:${{ github.sha }}
      - run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/demo:latest
      - run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/demo:${{ github.sha }}