name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - run: docker build -f Dockerfile -t ${{ secrets.DOCKER_HUB_USERNAME }}/demo:latest ./
      - run: GIT_SHA="$(git rev-parse --short HEAD)"
      - run: docker tag ${{ secrets.DOCKER_HUB_USERNAME }}/demo:latest ${{ secrets.DOCKER_HUB_USERNAME }}/demo:$GIT_SHA
      - run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/demo:latest
      - run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/demo:$GIT_SHA